### ISSUE TITLE
Drawer not close in outside touch 

### ISSUE THREAD

**Issue by MayurDev** [mxn21/FlowingDrawer#1]
Thanks for great work.
How can close drawer in outside touch of drawerlayout?

**Comment by mxn21** [comment]
you can call the method 'mLeftDrawerLayout.closeDrawer()' to close drawer automatically.
I hope it can help you solve the problems.

**Comment by mxn21** [comment]
actually outside touch can't  close drawer.
outside touch do not have effect in drawer

**Comment by eling13** [comment]
outside touch can scroll the fragement beside the drawer... please fix this bug , I like this drawer show.

**Comment by mxn21** [comment]
I have noticed that bug . I'm trying to fix it . I will complete soon.

**Comment by mxn21** [comment]
@eling13 this bug has been fixed already in 1.2 version.
use   
dependencies {
        compile 'com.mxn.soul:flowingdrawer-core:1.2.0'
    }
