### ISSUE TITLE
Drawer Issue

### ISSUE THREAD

**Issue by sanjaykumarm** [mxn21/FlowingDrawer#10]
![error](https://cloud.githubusercontent.com/assets/11767191/11468983/669f0502-9779-11e5-9f0f-5a941acb1713.png)

Please check the attached screen shot. There is white line at the right side left after drawer is opened. This line is random in shape and size and depends on at which speed you are opening the drawer.

Device : LG L7

**Comment by mxn21** [comment]
try to use genymotion or another mobile ,then check the   problem again please .

**Comment by moh586** [comment]
hi
i have same issue on my phone.i think the view shoud redraw at the end of animation

**Comment by parthanjaria** [comment]
Does anyone have any solution to this problem?

**Comment by moh586** [comment]
yes i found a solution 
at the first a declare a NavigationView in MyMenuFragment and bind it to R.id.vNavigation on onCreateView


and in the MainActivity i declare a OnNavigationItemSelectedListener and after showing menu set the listener to NavigationView  object of MyMenuFragment

**Comment by moh586** [comment]
i increase size of drawer and set right pading to 35dp

**Comment by mxn21** [comment]
@parthanjaria can you send your app demo to my gmail ? thanks

**Comment by gubaju** [comment]
I had similar issues but solved it (sorta) by using match parent instead of a fixed width inside

> RelativeLayout

 which is the parent of 

> com.mxn.soul.flowingdrawer_core.FlowingView

**Comment by mxn21** [comment]
you can use 2.0.0 that fixed it
