### ISSUE TITLE
NavigationDraweItemSelected

### ISSUE THREAD

**Issue by vutiendung** [mxn21/FlowingDrawer#12]
I want create method onNavigationItemSelected but i don't know make it where and how ? 
Please help me 
Sorry, my english is not good

**Comment by mxn21** [comment]
try to make setNavigationItemSelectedListener in MyMenuFragment$onCreateView.

@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
View view = inflater.inflate(R.layout.fragment_menu, container,
false);
ivMenuUserProfilePhoto = (ImageView) view.findViewById(R.id.ivMenuUserProfilePhoto);
NavigationView vNavigation = (NavigationView) view.findViewById(R.id.vNavigation);
vNavigation.setNavigationItemSelectedListener(new NavigationView.OnNavigationItemSelectedListener() {
@Override
public boolean onNavigationItemSelected(MenuItem menuItem) {
return false;
}
}) ;
setupHeader();
return setupReveal(view) ;
}

**Comment by rhyodhan** [comment]
Thanks For Your Solution, 
How can i call another fragment after use 
" public boolean onNavigationItemSelected(MenuItem menuItem) {
return false;
} ";  ?

i want to open another fragment after i chose drawer_menu.

**Comment by vutiendung** [comment]
the same question with @rhyodhan

**Comment by moh586** [comment]
the same question
how to set onnavigationitemselected listner in Activity that use mymenuFragment?

**Comment by alafandiomar** [comment]
@vutiendung have u been able to solve it ??

**Comment by moh586** [comment]
@alafandiomar hi yes i was able to solve this problem.i declare an object of NavigationView in the MyMenuFragment and in the Main Activity i have declare a NavigationView.OnNavigationItemSelectedListener object that get the item clicked.
at the end i call mMenuFragment.vNavigation.setNavigationItemSelectedListener(navlistner); on toolbar onclick listener.i sent my file for better undrestanding
sorry for delay and bad english
[MyMenuFragment.txt](https://github.com/mxn21/FlowingDrawer/files/187486/MyMenuFragment.txt)
[MainActivity.txt](https://github.com/mxn21/FlowingDrawer/files/187490/MainActivity.txt)

**Comment by alafandiomar** [comment]
yes thank u very much i solved it too but by using fragments and interfaces .... if u want fragments instead of activities tell and ill send it to u :D @moh586 thanks

**Comment by AhmedDonkl** [comment]
@alafandiomar could you please send me your solution using fragments and interfaces thanks

**Comment by alafandiomar** [comment]
@AhmedDonkl sure thing when i get home :D

**Comment by hemraj5** [comment]
how to make left drawer items clickable .......

**Comment by amit-upadhyay-IT** [comment]
@moh586  : I would like to suggest a better way for the implementation of OnNavigationItemSelectedListener. 

public class MyMenuFragment extends MenuFragment {

    private ImageView ivMenuUserProfilePhoto;
    public NavigationView navigationView;
    private LeftDrawerLayout mLeftDrawerLayout;
    AmitCallbackWhenDrawerOpens amitCallbackWhenDrawerOpens;

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }


    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        amitCallbackWhenDrawerOpens = (AmitCallbackWhenDrawerOpens) context;
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_menu, container,
                false);

        View view1 = inflater.inflate(R.layout.activity_main, container,
                false);
        mLeftDrawerLayout = (LeftDrawerLayout) view1.findViewById(R.id.id_drawerlayout);

        navigationView = (NavigationView) view.findViewById(R.id.vNavigation);

        //View navHeader = navigationView.getHeaderView(0); using when we are using support library greater than 23.0.0
 

        return  setupReveal(view) ;
    }

    public void onOpenMenu(){
        if (amitCallbackWhenDrawerOpens!= null)
            amitCallbackWhenDrawerOpens.drawerIsOpen();
        Toast.makeText(getActivity(),"onOpenMenu",Toast.LENGTH_SHORT).show();
    }
    public void onCloseMenu(){
        Toast.makeText(getActivity(),"onCloseMenu",Toast.LENGTH_SHORT).show();
    }

    public interface AmitCallbackWhenDrawerOpens {
        void drawerIsOpen();
    }
}

----------------------------------------------------------------------------------------------------------------

public class MainActivity extends AppCompatActivity implements MyMenuFragment.AmitCallbackWhenDrawerOpens{

@Override
    public void drawerIsOpen() {
        mMenuFragment.navigationView.setNavigationItemSelectedListener(navlistner);
    }
}

Benefits : 

This enables the OnNavigationItemSelected even if someone slides the drawer
