### ISSUE TITLE
Not Working With Eclipse

### ISSUE THREAD

**Issue by raviraghav93** [mxn21/FlowingDrawer#14]
Hi i've downloaded this and copy and pasted it in eclipse and made all the changes required and added all the libraries and project is showing no error but when i run it app is carshing and logcat is showing error on MainActivity's setcontentview with error in this attached file.
Please Help
[log.txt](https://github.com/mxn21/FlowingDrawer/files/105449/log.txt)

**Comment by mxn21** [comment]
you need android.support.v7.design.widget.CoordinatorLayout. check it in your library .
