### ISSUE TITLE
how to set menu in right of screen

### ISSUE THREAD

**Issue by siavash-sajjad** [mxn21/FlowingDrawer#18]
hi
i wanna set menu in right of screen and open from right to left. is it possible?

**Comment by mxn21** [comment]
no , it's not support right now. sorry .

**Comment by siavash-sajjad** [comment]
if i want to support this option(set menu in right of screen), what should i do?
please help me to add this option to your library

**Comment by mxn21** [comment]
it will maybe cost too much work.first , in LeftDrawerLayout's onLayout method , put mLeftMenuView to right . and then a lot of x coordinate need to adjust . I'm not willing to do this in 1.X version .
I will restructure the library  in 2.x version , and maybe will not use ViewDragHelper .
when I finish 2.x version i will add this option , but I can't promise   it will take how long .

**Comment by siavash-sajjad** [comment]
sorry but i don't understand 

> put mLeftMenuView to right . and then a lot of x coordinate need to adjust .
