### ISSUE TITLE
Glitch while opening the Drawer

### ISSUE THREAD

**Issue by parthanjaria** [mxn21/FlowingDrawer#19]
I am able to implement everything successfully. The only issue i am facing is a small glitch. I have attached the image of the glitch. Please if anyone has a solution please help me.

![img_20160220_143828387](https://cloud.githubusercontent.com/assets/14540386/13195818/76e7923c-d7e1-11e5-9b69-4216b03069ac.png)

**Comment by mxn21** [comment]
please send a demo to my gmail, I can't  reproduce this problem . thanks .

**Comment by parthanjaria** [comment]
here is attachment to the file :

​
 CustomNavigation.rar
<https://drive.google.com/file/d/0B5VHc_ky8FTxR3ZzRU1FQlJ5QlU/view?usp=drive_web>
​
please check the issue and help me out, if i find any solution i will let u
know

**Comment by MhtSuthar** [comment]
hi, plz let me know if resolve this issue coz i m facing this issue.

**Comment by gubaju** [comment]
I had similar issues but solved it (sorta) by using match parent instead of a fixed width inside

> RelativeLayout

 which is the parent of 

> com.mxn.soul.flowingdrawer_core.FlowingView

**Comment by theWakeningDog** [comment]
How to solve this question? Please tell me.

**Comment by mxn21** [comment]
you can use 2.0.0 that fixed it . sorry for this problem
