### ISSUE TITLE
how to get Navigation View in main activity

### ISSUE THREAD

**Issue by parthnvs** [mxn21/FlowingDrawer#2]
I am trying To set setNavigationItemSelectedListener on vNavigation in main activity.
but it is giving me nullexception.
please tell me how to do so

**Comment by mxn21** [comment]
try to setNavigationItemSelectedListener in MyMenuFragment$onCreateView.

 @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_menu, container,
                false);
        ivMenuUserProfilePhoto = (ImageView) view.findViewById(R.id.ivMenuUserProfilePhoto);
       NavigationView vNavigation = (NavigationView) view.findViewById(R.id.vNavigation);
        vNavigation.setNavigationItemSelectedListener(new NavigationView.OnNavigationItemSelectedListener() {
            @Override
            public boolean onNavigationItemSelected(MenuItem menuItem) {
                return false;
            }
        }) ;
        setupHeader();
        return  setupReveal(view) ;
    }

**Comment by parthnvs** [comment]
that worrks Thank You
