### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by VforViolet** [mxn21/FlowingDrawer#27]
Unable to have the following in my app manifest:
android:allowBackup="false"

Please fix this by removing the allowBackup attribute, thank you!

**Comment by mxn21** [comment]
thank you for report ,I noticed this problem， and will update library soon .

**Comment by VforViolet** [comment]
Thank you! (:

**Comment by mxn21** [comment]
you can use  compile 'com.mxn.soul:flowingdrawer-core:1.2.5'  and fix this .
