### ISSUE TITLE
circular on close 

### ISSUE THREAD

**Issue by Nightprince** [mxn21/FlowingDrawer#29]
hi , how to disable circular on close drawer ?

**Comment by mxn21** [comment]
sorry，don't support it right now

**Comment by Nightprince** [comment]
can add this method for drawer ?

**Comment by mxn21** [comment]
sure，I can add it in next version ,  it need some time.

**Comment by Nightprince** [comment]
ty . please add this and can you bring rtl support in new version?

**Comment by mxn21** [comment]
ok，I will try.

**Comment by mxn21** [comment]
fix circular on close drawer already on 2.0.0 . but it also has some circular
