### ISSUE TITLE
Can i open this Drawer from right ?

### ISSUE THREAD

**Issue by abumoallim** [mxn21/FlowingDrawer#30]

**Comment by dehghanimeh** [comment]
Yes ,How can i open this Drawer from right ?

**Comment by soheilghanbari1371** [comment]
thanks for this beuatiful code
but how to use it RTL
thanks

**Comment by mxn21** [comment]
ok,I'll add in next version

**Comment by mxn21** [comment]
you can use Drawer from right on 2.0.0 version
