### ISSUE TITLE
How can I make the drawer overlap the title bar ?

### ISSUE THREAD

**Issue by tudor07** [mxn21/FlowingDrawer#37]
Hi,

I wonder how can I make the drawer to fit all the screen height so it overlaps the title bar and also the status bar.

This is how it looks now: ![drawer](http://i.imgur.com/qaGIapl.png)

I want the drawer to be all the way up overlapping the title bar.

Thanks.

**Comment by mxn21** [comment]
FlowingDrawer will always fit all the screen height and  overlaps the title bar(toolbar) ,but not the status bar.

**Comment by tudor07** [comment]
But in my case (as you can see in the picture) the FlowingDrawer does not overlay the title bar(toolbar). Is this a default behavior ? Because it does not work by default for me.

**Comment by mxn21** [comment]
I guess your xml file is not correct. please read README or refer to demo

**Comment by tudor07** [comment]
Thanks for your fast response.
This is my activity_main.xml:
`<com.mxn.soul.flowingdrawer_core.FlowingDrawer
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/drawerlayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clipChildren="false"
    android:clipToPadding="false"
    app:edPosition="1"
    app:edMenuSize="260dp"
    app:edMenuBackground="#dddddd">

    
    <RelativeLayout
        android:id="@+id/content"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <RelativeLayout
            android:id="@+id/fragment_container"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

        <Button
            android:id="@+id/pair_try_again"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/try_again"
            android:layout_centerHorizontal="true"
            android:visibility="gone"/>

    </RelativeLayout>

    
    <com.mxn.soul.flowingdrawer_core.FlowingMenuLayout
        android:id="@+id/menulayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <RelativeLayout
            android:id="@+id/id_container_menu"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <TextView
                android:id="@+id/home"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="HOME"/>

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="SETTINGS"
                android:layout_below="@id/home"/>
        </RelativeLayout>

    </com.mxn.soul.flowingdrawer_core.FlowingMenuLayout>

</com.mxn.soul.flowingdrawer_core.FlowingDrawer>`

I don't really see anything wrong with it.

**Comment by mxn21** [comment]
well, check out your mainActivity's style , in my demo I use Theme.AppCompat.Light.NoActionBar

**Comment by tudor07** [comment]
Ohh I understand. I use Theme.AppCompat.Light.DarkActionBar.
So I should make a custom ActionBar and make it stay below the FlowingDrawer as there is no customization option for the FlowingDrawer itself ?

**Comment by mxn21** [comment]
yes ,you are right . @tudor07

**Comment by tudor07** [comment]
Ok I understand. 
Thank you very much for your time and fast responses. 
This issue can be closed then. :)

**Comment by usergoodvery** [comment]
Hi,
Is it actually a "mistake" to display below the toolbar? In my case that's a requirement.

regards,
