### ISSUE TITLE
[Bug] Child elements do not inherit the bounce effect

### ISSUE THREAD

**Issue by tudor07** [mxn21/FlowingDrawer#38]
Hi,

I think this is a bug.
So when the bouncing effect occurs the child elements do not act accordingly.

Please check the images: http://imgur.com/a/oKY5L

On the bounce effect the blue square does not bounce too.

Also when opening the FlowingDrawer you can see the margin line is not smooth and has some outlines from the parent.

Do you think you can fix this ?

**Comment by tudor07** [comment]
I found out the solution.
android:clipChildren="true"

Setting this to true will make it work.
Sorry :D

**Comment by mxn21** [comment]
This happens because you have two parts of menu layout ,and they have two different backgrounds:blue and white .  You should keep their background be the same . It means menu layout should have only one background and the only way to set is app:edMenuBackground="#dddddd" .

**Comment by mxn21** [comment]
and make sure: android:clipChildren="false"

**Comment by tudor07** [comment]
Yes but I want to have that blue square. 
It works with clipChildren=true

**Comment by woai110120130** [comment]
hi, 想求教下你绘制贝塞尔曲线曲线的算法是怎么生成的，对于连个贝塞尔曲线合成一个曲线，比较好奇，有什么好的方法吗？求分享

**Comment by mxn21** [comment]
@woai110120130 通过观察和调整确定控制点的位置，我的方法也不一定是最好的，只是可以做到正常展示而已。
