### ISSUE TITLE
Ripple effect not showing

### ISSUE THREAD

**Issue by Ashwani270292** [mxn21/FlowingDrawer#52]
I imported this library using gradle, added its view as shown in sample. but the ripple effect from menu is gone. in sample app its working,but i am implementing the same it is not. Is there any thing i am missing?

**Comment by Hanzala717** [comment]
I got same problem I used sample app and when clicked on "photos you've liked" effect shows on "news"
and when clicked "photos nearby" effect shows on "Instagram Direct" and so on...

**Comment by Ashwani270292** [comment]
In my case effect is not shown in any case, i am using build 25, the library is made on 22, so should i downgrade my application build?
