### ISSUE TITLE
duplicate entry exception while using with multidexenable true

### ISSUE THREAD

**Issue by Arvind8858** [mxn21/FlowingDrawer#53]
I am adding google login in my app and also using floating drawer but when I am using multidexenable true due to google-play-services library then its gives me error. 

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/mxn/soul/flowingdrawer_core/BuildConfig.class

My gradle file is- 
apply plugin: 'com.android.application'

android {
    
    compileSdkVersion 25
    buildToolsVersion "26.0.0"
    defaultConfig {
        applicationId "XXXX"
        minSdkVersion 18
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
       multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    configurations.all {
        resolutionStrategy.force 'com.google.code.findbugs:jsr305:1.3.9'
    }

}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile project(':flowingdrawer-core')
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support:recyclerview-v7:25.3.1'
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.google.android.gms:play-services-location:10.2.0'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.synnapps:carouselview:0.1.4'
    compile 'com.azoft.carousellayoutmanager:carousel:1.2.1'
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile 'org.apache.httpcomponents:httpcore:4.4.1'
    compile 'org.apache.httpcomponents:httpclient:4.5'
    compile 'com.mxn.soul:flowingdrawer-core:2.0.0'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'com.squareup.picasso:picasso:2.5.0'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.google.code.gson:gson:2.6.2'
    compile 'com.github.apl-devs:appintro:v4.2.0'
    compile 'com.facebook.android:facebook-android-sdk:[4,5)'
    compile 'com.google.android.gms:play-services-auth:10.2.0'
    compile 'com.google.api-client:google-api-client:1.22.0'
    compile 'com.google.api-client:google-api-client-android:1.22.0'
    compile 'com.google.apis:google-api-services-people:v1-rev4-1.22.0'
    compile 'com.android.support:multidex:1.0.0'
    testCompile 'junit:junit:4.12'
}
android {
    useLibrary 'org.apache.http.legacy'

}
apply plugin: 'com.google.gms.google-services'

Hope for solution ASAP.

**Comment by mxn21** [comment]
delete compile project(':flowingdrawer-core')   because you have added the library by this:compile 'com.mxn.soul:flowingdrawer-core:2.0.0'
