### ISSUE TITLE
Failed to find style 'elasticDrawerStyle' in current theme

### ISSUE THREAD

**Issue by Yavar007** [mxn21/FlowingDrawer#55]
Hi,
when i want to add this library to my projects i get these errors:

--Failed to find style 'elasticDrawerStyle' in current theme
--Missing styles. Is the correct theme chosen for this layout?  Use the Theme combo box above the layout to choose a different layout, or fix the theme style references. 
--The graphics preview in the layout editor may not be accurate: 
   - Paint Flags Draw Filters are not supported.

**Comment by mxn21** [comment]
check flowingdrawer-core > res > values > attrs.xml 
    <attr name="elasticDrawerStyle" format="reference" />  need to be added in attrs.xml

**Comment by FedGk** [comment]
这个问题应该不影响开发的吧？因为我在看你提供的demo时。ide一样报这个错误。而且我尝试了很多方法，始终无法去掉这个报错。
