### ISSUE TITLE
The RTL

### ISSUE THREAD

**Issue by abdulmalekDery** [mxn21/FlowingDrawer#58]
-is there any way to change the direction of the amazing FlowingDrawer to let it open from the right side of the screen?

**Comment by mxn21** [comment]
Use edPosition attribute corresponding to which side of the view you want the drawer to emerge from: left or right.Left menu : edPosition =1 ; Right menu: edPosition =2 .

**Comment by abdulmalekDery** [comment]
thank you very much
but is there any way to change that attribute from the java code?
