### ISSUE TITLE
Android P devices

### ISSUE THREAD

**Issue by gtaricsi** [mxn21/FlowingDrawer#62]
There is a bug which causes that FlowingDrawer is not compatible with Android P devices:
just change "canvas.clipPath(mClipPath, Region.Op.REPLACE);" to "canvas.clipPath(mClipPath, Region.Op.INTERSECT);" and it will work like a charm.

Thank you

**Comment by PDesire** [comment]
Same problem occurring here on Pixel 2 XL Android 9 DP5

**Comment by ShengjieGeng** [comment]
yeah ,I got a IllegalArgumentException too
![qq 20181204174639](https://user-images.githubusercontent.com/18364968/49433277-993c2b80-f7ec-11e8-9d11-a7498365ffb9.png)

**Comment by yanchengdeng** [comment]
> There is a bug which causes that FlowingDrawer is not compatible with Android P devices:
> just change "canvas.clipPath(mClipPath, Region.Op.REPLACE);" to "canvas.clipPath(mClipPath, Region.Op.INTERSECT);" and it will work like a charm.
> 
> Thank you

solve my problem!thx!

**Comment by jansvanda** [comment]
https://github.com/jansvanda/FlowingDrawer/commit/d5b37b86a43a683b93ad1845e3785a769a45fbe2

**Comment by wanghao15536870732** [comment]
> > There is a bug which causes that FlowingDrawer is not compatible with Android P devices:
> > just change "canvas.clipPath(mClipPath, Region.Op.REPLACE);" to "canvas.clipPath(mClipPath, Region.Op.INTERSECT);" and it will work like a charm.
> > Thank you
> 
> solve my problem!thx!

File is not writeable....

**Comment by mxn21** [comment]
I have solved this problem with this commit ：https://github.com/mxn21/FlowingDrawer/commit/e647498f8b5c1639bd5aecb871d408e7ddc9a7fa
Please use the latest version 2.1.0
