### ISSUE TITLE
After open Drawer,the right arch still remain

### ISSUE THREAD

**Issue by DimlyDiscernible** [mxn21/FlowingDrawer#7]
the emulator is sdk/eclipse's  default , API is 16. like this

![qq 20151031185856](https://cloud.githubusercontent.com/assets/15519781/10863231/a4b01f6e-8001-11e5-8146-2f8ff42aea7d.png)

I don't know this problem is emulator's or not, 因为源码还没看懂...

**Comment by mxn21** [comment]
检查一下布局，

        <RelativeLayout
            android:layout_width="280dp"
            android:layout_height="match_parent"
            android:layout_gravity="start"
            android:clipChildren="false"
            >
            <com.mxn.soul.flowingdrawer_core.FlowingView
                android:id="@+id/sv"
                android:layout_width="match_parent"
                android:layout_height="match_parent"/>
            <FrameLayout
                android:id="@+id/id_container_menu"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_alignParentLeft="true"
                android:layout_marginRight="25dp"
                android:paddingRight="10dp"
                />
        </RelativeLayout>

menuframent  的布局要设置透明。
你能把你改动的代码贴上来吗

**Comment by DimlyDiscernible** [comment]
没有太大的改动，只是因为没升级android support library，没法用material design所以把activity_main布局里的CoordinatorLayout注释掉换了个空的LinearLayout，menufragment的布局也是注释掉了NavigationView，改成了三个textView。

运行出现这个问题后，我又加上了ActionBar，测试点击左上角后调用mLeftDrawerLayout.openDrawer() 会不会出现问题，结果是点一次还是这样，不过再点一次的话那个弧形就消失了，onOptionsItemSelected()里就只调用了mLeftDrawerLayout.openDrawer()。

**Comment by mxn21** [comment]
最好能把代码放上来，我怀疑你的mainActivity代码或者布局有问题。按照Usage下面的注意事项一一对照。

**Comment by DimlyDiscernible** [comment]
刚装了genymotion，运行一切正常，看来只是自带模拟器的问题，可能是那模拟器略卡导致重画没画好吧
= =
