### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Nilkesh310307** [mxn21/FlowingDrawer#70]
Not work in 9.0
invalid region.op - only intersect and difference

**Comment by mxn21** [comment]
Are you using the latest version?

**Comment by Udayraj123** [comment]
Issue is happening for version 2.0.0 
Testing with 2.1.0 now (as per https://github.com/mxn21/FlowingDrawer/issues/65)

**Comment by Udayraj123** [comment]
Confirmed on multiple devices the issue is solved with the 2.1.0 patch
