### ISSUE TITLE
Invalid Region.Op - only INTERSECT and DIFFERENCE

### ISSUE THREAD

**Issue by tareq3** [mxn21/FlowingDrawer#73]
Showing error Invalid Region.Op - only INTERSECT and DIFFERENCE on Android Pie.

![image](https://user-images.githubusercontent.com/18117310/64078944-f96fe780-cd02-11e9-844a-d318a7c7dd37.png)

**Comment by mxn21** [comment]
I have solved this problem with this commit ：e647498
Please use the latest version 2.1.0

**Comment by tareq3** [comment]
It Worked. Thanx a lot
