### ISSUE TITLE
MenuFragment cannot find view with appcompat-v7:23.1.0 or higher

### ISSUE THREAD

**Issue by quanlt** [mxn21/FlowingDrawer#8]
view.findViewById in MenuFragment doesn't work with appcompat-v7:23.1.0 +, design:23.1.0+, and so on.
//I should use navigationView.getHeaderView(0) to get view from header.so, it's not your issue.
delete it please :dancers:

**Comment by mxn21** [comment]
I don't find something wrong with appcompat-v7:23.1.0 or higher in my demo .

**Comment by bicho** [comment]
Same that @quanlt with appcompat-v7:23.1.+ i used on MyMenuFragment: 

 ```
View view = inflater.inflate(R.layout.fragment_menu, container, false);
NavigationView navigationView = (NavigationView) view.findViewById(R.id.vNavigation);
ivMenuUserProfilePhoto = (ImageView) navigationView.getHeaderView(0).findViewById(R.id.ivMenuUserProfilePhoto);
```

regards.
